### ISSUE TITLE
Highlight "extra fields"

### ISSUE THREAD

**Issue by paulwelscott** [joshwhatk/better-jira#11]
As a jira user, I would like to have extra fields (e.g. label, component) of a Jira card highlighted in the Board view so that I can quickly see what extra fields are on a Jira card.

Before:

![screen shot 2019-01-28 at 12 51 17 pm](https://user-images.githubusercontent.com/12339852/51859025-c8a67a80-22fb-11e9-8b10-12677268d47f.png)

After:

![screen shot 2019-01-28 at 12 53 09 pm](https://user-images.githubusercontent.com/12339852/51859037-d0661f00-22fb-11e9-9ab8-d15efaf6cddf.png)

**Comment by brandonraydev** [comment]
@paulwelscott I believe this is already a feature of Jira at this point.
