### ISSUE TITLE
Jira did update the html code and, the column fixed width feature is broken

### ISSUE THREAD

**Issue by chuprik** [joshwhatk/better-jira#42]
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/802946/180773882-a00a2837-9005-48ea-9603-c304e30c8926.png">

**Comment by joshwhatk** [comment]
Thanks, @kotchuprik! I will look into this.

**Comment by brandonraydev** [comment]
@kotchuprik this one is actively being worked on and we should have an update for this soon!

**Comment by brandonraydev** [comment]
Merged to repo. Needs to be built to app stores.

**Comment by brandonraydev** [comment]
Update submitted to Chrome/Firefox stores. Should be out soon.
