### ISSUE TITLE
Add quick pullable toggle

### ISSUE THREAD

**Issue by joshwhatk** [joshwhatk/better-jira#5]
Idea from Cory Mabry:

Double clicking the card toggles it pullable / not pullable.

(Single click still opens the card normally).

**Comment by brandonraydev** [comment]
@joshwhatk this is an interesting idea. I think it would become complex depending on how the individual boards are setup. For example, some boards could move to different "next" pullable states. Also, some permissions may prevent people from taking their cards backwards. As such, I think this could become dangerous with unintentional double-clicks. Thoughts?
